const chromium = require('@sparticuz/chromium');
const puppeteer = require('puppeteer-core');

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  try {
    const { score = 0, name = '', email = '', company = 'Your Business', industry = '', breakdown = [] } = JSON.parse(event.body || '{}');

    const html = buildHtml({ score, name, email, company, industry, breakdown });

    const executablePath = await chromium.executablePath();
    const browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath,
      headless: chromium.headless,
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      printBackground: true,
      format: 'Letter',
      margin: { top: '20mm', right: '16mm', bottom: '20mm', left: '16mm' }
    });
    await browser.close();

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="Exit-Score.pdf"'
      },
      body: pdf.toString('base64'),
      isBase64Encoded: true
    };
  } catch (e) {
    return { statusCode: 500, body: JSON.stringify({ error: e.message }) };
  }
};

function buildHtml({ score, name, email, company, industry, breakdown }) {
  const primary = '#101620';
  const accent = '#416EA6';
  const light = '#F0F1F2';
  const logoUrl = 'https://score.arxbrokers.com/arx_website_blueblack.webp';

  const rows = breakdown.map(b => `
    <tr>
      <td style="padding:8px 12px; border-bottom:1px solid #e5e7eb;">${b.name}</td>
      <td style="padding:8px 12px; border-bottom:1px solid #e5e7eb; text-align:right; font-weight:600;">${b.percent}%</td>
    </tr>
  `).join('');

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
      <style>
        body { font-family: 'Open Sans', system-ui, -apple-system, Segoe UI, Roboto, sans-serif; color: #111827; }
        h1,h2,h3 { font-family: 'Inter', sans-serif; }
        .header { display:flex; align-items:center; justify-content:space-between; padding: 16px 0; border-bottom: 2px solid ${light}; }
        .brand { display:flex; align-items:center; gap:12px; }
        .score { font-size: 48px; font-weight: 700; color: ${accent}; }
        .chip { display:inline-block; background:${light}; color:${primary}; padding:4px 10px; border-radius:999px; font-size:12px; font-weight:600; }
        .section { margin-top: 20px; }
        .footer { margin-top: 24px; font-size: 12px; color: #6b7280; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="brand">
          <img src="${logoUrl}" alt="ARX" style="height:34px" />
          <div style="font-weight:800; font-size:18px; color:${primary};">ARX Business Brokers</div>
        </div>
        <div class="chip">Exit Score Report</div>
      </div>

      <div class="section">
        <h1 style="margin: 8px 0 0 0;">${company}</h1>
        <div style="color:#374151;">${industry || 'Industry N/A'}</div>
      </div>

      <div class="section" style="display:flex; align-items:center; gap:16px;">
        <div class="score">${score}%</div>
        <div>Overall Sales Readiness Score</div>
      </div>

      <div class="section">
        <h3>Category Breakdown</h3>
        <table style="width:100%; border-collapse: collapse; margin-top: 8px;">
          ${rows}
        </table>
      </div>

      <div class="footer">
        Prepared for ${name || 'Client'} (${email || 'N/A'}) • Generated by score.arxbrokers.com
      </div>
    </body>
  </html>`;
}

