# Trigger redeploy: 2025-09-12T03:45Z
[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://www.googletagmanager.com https://connect.facebook.net https://snap.licdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.facebook.com https://px.ads.linkedin.com; connect-src 'self' https://api.anthropic.com https://*.netlify.app https://www.google-analytics.com https://www.google.com https://www.facebook.com https://px.ads.linkedin.com; frame-src https://www.google.com https://recaptcha.google.com;"

[functions]
  node_bundler = "esbuild"

[functions."generate-pdf"]
  # Increase resources for headless Chromium
  timeout = 26
  memory = 1536
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
